### ISSUE TITLE
After update to version 3.1.28, templates cannot be loaded

### ISSUE THREAD

**Issue by yourchoice** [smarty-php/smarty#134]
After update to version 3.1.28, templates cannot be loaded:

Fatal error: Uncaught --> Smarty: Unable to load template file 'admin/index.tpl' <-- thrown in E:\_prjutils\lib3\smarty\sysplugins\smarty_internal_template.php on line 139.

**Comment by GAngZta85** [comment]
Use setTemplateDir() 
The method $template_dir is now private

**Comment by yourchoice** [comment]
I tried $smarty->setTemplateDir(ROOT_DIR . 'templates/'); but same error.

**Comment by uwetews** [comment]
$template_dir was private already already long time. An direct access to it should internally call setTemplateDir(). This was broken.
See  https://github.com/smarty-php/smarty/issues/121

Does constant ROOT_DIR include a trailing '/' ? 

Call $smarty->testInstall(); after setTemplateDir() to check the folder setup

**Comment by yourchoice** [comment]
Hi, 

Thank you for answers.

Before i had smarty 3.1.27 and worked with:
>>
...
define('ROOT_DIR', '/airway/');
...
$smarty->template_dir = ROOT_DIR . 'templates/';
$smarty->compile_dir = ROOT_DIR . 'tmp/templates_c/';
$smarty->config_dir = ROOT_DIR . 'templates/configs/';
$smarty->cache_dir = $smarty->compile_dir . 'cache/';
....
<<

Seems that the problem is ROOT_DIR definition. With: "define('ROOT_DIR', 'E:/airway/');" and set methods working. Maybe better if work and with : "define('ROOT_DIR', '/airway/');"

Thank's.

**Comment by uwetews** [comment]
Recheck your example with the updated version in the master branch. It should work now same way as in 3.1.27

**Comment by iquito** [comment]
This also broke my application - using setTemplateDir instead of the template_dir variable fixed it for now. Maybe there should be a bugfix release, because a lot of applications could have the same problems when updating.

**Comment by iquito** [comment]
Actually, setTemplateDir does not solve the problem - Smarty then creates the templates_c directory in my root project directory and writes all files in there, the directory I set with setTemplateDir is not used. Smarty also attempts to do the same when setting the template_dir variable (it also creates the template_c directory in project root) but then it does not find its own templates.

**Comment by uwetews** [comment]
setTemplateDir() does set up the template_dir not compile_dir (template_c).
The later is set by setCompileDir().

We will soon release 3.1.29 with bugfixes

**Comment by uwetews** [comment]
define('ROOT_DIR', '/airway/');
did confuse Smarty as you used the Linux separator '/' and it looked like an absolute path.
define('ROOT_DIR', './airway/');
should work.

But I will add additional checks for the OS type.

**Comment by uwetews** [comment]
Te fix is now in the master branch

**Comment by uwetews** [comment]
Now it got it. a path like '/airway/' on windows should normalize to the root dir of the current working drive. This is now fixed in the master branch.
